#!/usr/bin/env bash


python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "assist2009"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "assist2009-full"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "assist2012"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "assist2015"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "assist2017"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "algebra2005"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "algebra2006"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "algebra2008"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "bridge2algebra2006"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "bridge2algebra2008"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "edi2020-task1"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "edi2020-task34"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "SLP-bio"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "SLP-chi"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "SLP-eng"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "SLP-mat"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "SLP-phy"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "SLP-his"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "SLP-geo"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "slepemapy"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "xes3g5m"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "statics2011"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "junyi2015"
python F:/code/myProjects/dlkt/example/preprocess.py --dataset_name "poj"

