python F:/code/myProjects/dlkt/example/train/qdkt_output_enhance.py \
  --setting_name "our_setting" --dataset_name "assist2009" --data_type "only_question" \
  --train_file_name "assist2009_train_fold_0.txt" --valid_file_name "assist2009_valid_fold_0.txt" --test_file_name "assist2009_test_fold_0.txt" \
  --optimizer_type "adam" --weight_decay 0.001 --momentum 0.9 \
  --train_strategy "valid_test" --num_epoch 200 \
  --use_early_stop True --epoch_early_stop 10 --use_last_average False --epoch_last_average 5 \
  --main_metric "AUC" --use_multi_metrics False \
  --learning_rate 0.001 --enable_lr_schedule False --lr_schedule_type "MultiStepLR" --lr_schedule_step 10 --lr_schedule_milestones "[5]" --lr_schedule_gamma 0.5 \
  --train_batch_size 64 --evaluate_batch_size 256 \
  --enable_clip_grad False --grad_clipped 10.0 \
  --num_concept 123 --num_question 17751 \
  --dim_concept 64 --dim_question 64 --dim_correct 64 --dim_latent 64 --rnn_type "gru" --num_rnn_layer 1 --dropout 0.3 --num_predict_layer 3 --dim_predict_mid 128 --activate_type "relu" \
  --enhance_method 2 \
  --weight_enhance_loss1 1 --num_min_question4diff 100 --hard_acc 0.4 --easy_acc 0.8 \
  --weight_enhance_loss2 1 --enhance_method2_update_few_shot True --num_few_shot 5 \
  --use_LLM_emb4question False --use_LLM_emb4concept False --train_LLM_emb True \
  --save_model False --seed 0